_java_build: &java_build
  language: java
  script: ./gradlew build

jobs:
  include:
    - stage: "Build"
      name: "Sphinx Docs (HTML)"
      language: python
      python: 3.8
      install:
        - pip install sphinx sphinx_rtd_theme recommonmark
      script:
        - cd docs
        - make html
    - jdk: oraclejdk11
      <<: *java_build
    - jdk: openjdk11
      <<: *java_build
    - jdk: openjdk13
      <<: *java_build


after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL