addons:
  artifacts:
    # ⋮
    paths:
      - ./build
      - ./docs/_build

jobs:
  include:
    - stage: "Build"
      name: "Sphinx Docs (HTML)"
      language: python
      python: 3.8
      install:
        - pip install sphinx sphinx_rtd_theme recommonmark
      script:
        - cd docs
        - make html
    - language: java
      jdk: oraclejdk11
      script: ./gradlew build
    - language: java
      jdk: openjdk11
      script: ./gradlew build


after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL