env:
  - ARTIFACTS_DIR=$TRAVIS_BUILD_DIR/build/artifacts/

addons:
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}
    target_paths:
      - /${TRAVIS_BRANCH}
      - /${TRAVIS_COMMIT}

before_script:
  - mkdir -p $ARTIFACTS_DIR

jobs:
  include:
    - stage: "Build"
      name: "Sphinx Docs (HTML)"
      language: python
      python: 3.8
      install:
        - pip install sphinx sphinx_rtd_theme recommonmark
      script:
        - cd docs
        - make html
      after_script:
        - cp -R _build/ ${ARTIFACTS_DIR}/docs
    - language: java
      jdk: oraclejdk11
      script: ./gradlew build
      after_script:
        - cp -R build/ ${ARTIFACTS_DIR}/build/
    - language: java
      jdk: openjdk11
      script: ./gradlew build
      after_script:
        - cp -R build/ ${ARTIFACTS_DIR}/build/

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL